services:
  database:
    mem_limit: 2048m
    image: ${MYSQL_IMAGE} #Default: mariadb:latest 
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - wordpress-network  
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
  phpmyadmin:
    depends_on:
      - database
    image: ${PHPMYADMIN_IMAGE} #Default: phpmyadmin/phpmyadmin:latest
    restart: always
    env_file:
      - .env
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    networks:
      - wordpress-network
  wordpress:
    depends_on:
      - database
    image: ${WORDPRESS_IMAGE} #Default: wordpress:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
      WORDPRESS_CONFIG_EXTRA: '${WORDPRESS_CONFIG_EXTRA:-}'
    volumes:
      - ${VOLUME_PATH:-./wp-content}:/var/www/html/wp-content
      # - ./wp-config.php:/var/www/html/wp-config.php
    networks:
      - wordpress-network
      
  ftp:
    image: stilliard/pure-ftpd
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      FTP_USER_NAME: '${FTP_USER_NAME}'
      FTP_USER_PASSWORD: '${FTP_USER_PASSWORD}'
      FTP_PASSIVE_PORTS: '30000:30009'
      # Uncomment and set FTP_FORCE_PASSIVE_IP to your public IP or hostname if you are behind NAT
      # FTP_FORCE_PASSIVE_IP: 'YOUR_PUBLIC_IP_OR_HOSTNAME'
    volumes:
      # Mount the host's wp-content directory to the FTP user's home directory
      # This assumes your wp-content directory is located at ./wp-content relative to this docker-compose.yaml
      - ${VOLUME_PATH:-./wp-content}:/home/ftpuser/wp-content
    networks:
      - wordpress-network
    depends_on:
      - wordpress # Ensures WordPress is running before FTP starts

volumes:
  db-data:
networks:
  wordpress-network:
    driver: bridge
